name: Trigger propagation

on:
  push:
    branches: [ master ]

jobs:
  transform:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
    - name: Checkout Processed files
      uses: actions/checkout@master
      with:
        repository: sanskrit/ashtadhyayi_com_transforms
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        path: processed_data
        fetch-depth: 1 # Because of this, you will fail to push refs to dest repo
        ref: trigger_branch
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create local changes
      run: |
        cp ${HOME}/files*.json `pwd`/processed_data/change_details -nf
      # "We don't run this to avoid exposing emails: cp ${GITHUB_EVENT_PATH} `pwd`/processed_data/change_details -nf"
    - name: Commit changes
      env:
        TRANSFORM_REPO_TOKEN: ${{ secrets.VISH_TOKEN }}
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        printf "https://github.com/ashtadhyayi-com/data/actions/runs/$GITHUB_RUN_ID\nlast_commit_log: $(git log -1 --pretty=format:"%s")" > processed_data/change_details/current_run.md
        cd processed_data
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add --all
        git diff-index --quiet HEAD || git commit -m "Add changes" -a
        remote_repo="https://${GITHUB_ACTOR}:${TRANSFORM_REPO_TOKEN}@github.com/sanskrit/ashtadhyayi_com_transforms.git"
        git push "${remote_repo}" HEAD:trigger_branch|| (cd .. && git pull --rebase && git commit --allow-empty -m "Dummy commit to trigger workflow rerun upon 'push race condition'." && git push "https://${GITHUB_ACTOR}:${TRANSFORM_REPO_TOKEN}@github.com/${GITHUB_REPOSITORY}.git")
      # We want to ensure that there is some change in processed_data for every change in ashtadhyayi data - so that downstream listeners can hark to the corresponding trigger.
      # Race conditions (A push after the initial checkout above, triggered by successive pushes to this repo) happen. Ideally, we should be able to restart the workflow, but that is not possible currently as per https://github.community/t/is-it-possible-to-manually-force-an-action-workflow-to-be-re-run/2127/23 . Instead, we eliminate time consuming tasks (to reduce probability of race conditions here) and do a dummy commit to trigger a new run. 
      # Regarding the dummy commit: If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. So, we use the separate token.
